services:
  orchestator.webapi:
    image: orchestator.webapi
    build:
      context: .
      dockerfile: src/orchestator/Orchestrator.WebApi/Dockerfile

  payment.webapi:
    image: payment.webapi
    build:
      context: .
      dockerfile: src/payments/Payment.WebApi/Dockerfile
      
  sqlserverdb:
    image: "mcr.microsoft.com/mssql/server:2022-latest" 

  rabbitmq:
    image: "rabbitmq:management"

