services:
  orchestator.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8007
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__OrchestatorConnectionString=${ORCHESTATOR_CONNECTIONSTRING}
      - MessageBrokerOptions__Username=${RABBITMQ_USER}
      - MessageBrokerOptions__Password=${RABBITMQ_PASSWORD}
      - MessageBrokerOptions__ConnectionString=amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672
    ports:
      - 8007:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
      - my_network

  payment.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8008
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__PaymentConnectionString=${PAYMENT_CONNECTIONSTRING}
      - MessageBrokerOptions__Username=${RABBITMQ_USER}
      - MessageBrokerOptions__Password=${RABBITMQ_PASSWORD}
      - MessageBrokerOptions__ConnectionString=amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672
    ports:
      - 8008:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
      - my_network

  inventory.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8009
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__InventoryConnectionString=${INVENTORY_CONNECTIONSTRING}
      - MessageBrokerOptions__Username=${RABBITMQ_USER}
      - MessageBrokerOptions__Password=${RABBITMQ_PASSWORD}
      - MessageBrokerOptions__ConnectionString=amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672
    ports:
      - 8009:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
      - my_network


  sqlserverdb:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DATABASE_PASSWORD}
      - MSSQL_PID=Express
    ports:
      - 1433:1433
    volumes:
      - ${APPDATA}/Microsoft/SQLServer/data:/var/opt/mssql/data
      - ${APPDATA}/Microsoft/SQLServer/log:/var/opt/mssql/log
      - ${APPDATA}/Microsoft/SQLServer/secrets:/var/opt/mssql/secrets
    networks:
      - my_network

  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    networks:
      - my_network


networks:
  my_network:
    external: true